### PR TITLE
Fix spelling issues (javascript-integration-testing)

### PR DESCRIPTION
**Pull request by sfadriaan**
As per the issue raised in the Open Documentation Academy (Issue [77](https://github.com/canonical/open-documentation-academy/issues/77))

The page "Integration Testing in JavaScript" was removed from the exclusion list and `make spelling` was run to include it in the spell checker.

Spelling errors picked up were corrected in the relevant `.rst` file. A few notable changes:

* `Graded Browser Support`: From documentation on [this](https://clarle.github.io/yui3/yui/docs/tutorials/gbs/) website, it was concluded that it should be separate words vs one word
* `centred`: documentation should be in en-gb which prompted the change from `centered`
* `yuitest`: formatted the word as a coding block to keep it consistent throughout the document (see sub-section "Creating the tests" bullet point 2)
* `browser's`: This could have been interpreted incorrectly. Another acceptable change could have been `browsers'` which would indicate plural. The proposed change assumed it should be singular

Thanks

### CODE REVIEW

**Review by ineesalmeida — APPROVED** [review]
Looks great! Thanks for the clear explanation in the PR description!

**Comment by ineesalmeida** [comment]
Needs a rebase to be able to merge

**Comment by sfadriaan** [comment]
> Needs a rebase to be able to merge

@ineesalmeida is this something I need to do? Apologies - my Github jargon knowledge is growing by the day :-)

**Comment by ineesalmeida** [comment]
Merged :)

**Pull request merged**
