### PR TITLE
oda spelling check on contribute-to doc

### PR DESCRIPTION
**Pull request by gerryRcom**

### CODE REVIEW

**Comment by ineesalmeida** [comment]
@gerryRcom I just merged a commit to update that link, since it so often failed in link checks. If you rebase `main` this shouldn't be an issue anymore :crossed_fingers:

**Comment by gerryRcom** [comment]
I "think" I did that? but it's still failing, not sure I'm reading the error right, looks like this might be the cause? or did I do something wrong on the re-sync?

Strange thing is, the 502 reported links work fine for me

```
(how-to/debug-tests-with-visual-studio-code: line   93) broken    https://code.visualstudio.com/docs/editor/debugging - 502 Server Error: Bad Gateway for url: https://code.visualstudio.com/docs/editor/debugging
(explanation/branches: line   22) ok        https://code.launchpad.net/~launchpad/launchpad/+git/launchpad/+ref/db-stable
(how-to/debug-tests-with-visual-studio-code: line   89) broken    https://code.visualstudio.com/docs/python/debugging - 502 Server Error: Bad Gateway for url: https://code.visualstudio.com/docs/python/debugging

```

**Comment by ineesalmeida** [comment]
Oh, this one seems like a different link has issues... I suspect it was a one time thing, possibly a code.visualstudio.com deployment of some sorts. I'm re-run the failed checks, let's see

**Comment by gerryRcom** [comment]
Thanks @ineesalmeida looks good now :)

**Review by jugmac00 — APPROVED** [review]
Thank you!

**Pull request merged**
