### PR TITLE
Documentation for debugging tests with vscode integration

### PR DESCRIPTION
**Pull request by RuinedYourLife**
Explanation on how to configure your environment to start debugging tests interactively with visual studio code integration

### CODE REVIEW

**Review by jugmac00 — COMMENTED** [review]
This is a great start, but I think this misses the SSH part, right?

**Comment by RuinedYourLife** [comment]
> This is a great start, but I think this misses the SSH part, right?

forgot about this...
added a section for it

question: how can i make this new document appear in the "how-to" menu on the left?

**Comment by jugmac00** [comment]
> question: how can i make this new document appear in the "how-to" menu on the left?

You need to add the filename (without the file ending) to `how-to/index.rst`.

**Comment by RuinedYourLife** [comment]
> > question: how can i make this new document appear in the "how-to" menu on the left?
> 
> You need to add the filename (without the file ending) to `how-to/index.rst`.

thanks!

**Review by jugmac00 — APPROVED** [review]
Thanks a lot! I am looking forward to try this myself.

**Pull request merged**
