### PR TITLE
Add missing codehosting doc; fix broken link

### PR DESCRIPTION
**Pull request by nielsenjared**
This PR refers to https://github.com/canonical/open-documentation-academy/issues/78

It adds the missing "How To Use Codehosting Locally" page and fixes the corresponding link in `code.rst`. I put this file in the `/how-to` directory given the nature of its content, but let me know if it belongs elsewhere. Running `make linkcheck` throws a `toctree` error. Let me know if this needs to be added to an `index.rst`.

### CODE REVIEW

**Comment by jugmac00** [comment]
Yes, indeed - we need to add all newly added files to an index. Thank you!

**Comment by nielsenjared** [comment]
I added `codehosting-locally` under the "Launchpad development tips" in `how-to/index.rst`. Let me know if it belongs somewhere else. I'm no longer getting the `toctree` error, but I'm still getting this:
```
WARNING: unknown document: 'how-to/codehosting-locally' [ref.doc]
```
Let me know if I need to do anything to resolve it.

**Comment by jugmac00** [comment]
Thanks! I won't be able to look into it this week, but I will hope to be able to follow up soon after that.

**Comment by alvaro-crespo** [comment]
Thanks a lot for the contribution @nielsenjared ! FYI the warning was coming from `<../how-to/codehosting-locally>`, that was missing the `../`  when referencing the code hosting doc.

**Pull request merged**
